apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-backend
  namespace: hms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hms-backend
  template:
    metadata:
      labels:
        app: hms-backend
    spec:
      containers:
        - name: backend
          image: hms/backend:latest
          ports:
            - containerPort: 5000
