apiVersion: v1
kind: Secret
metadata:
  name: hms-secrets
  namespace: hms
type: Opaque
stringData:
  MONGODB_URI: replace_me
  REDIS_URL: replace_me
  JWT_ACCESS_SECRET: replace_me
  JWT_REFRESH_SECRET: replace_me
